import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Provider from "@/components/Provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <Navbar />
          <div className="container h-full pt-6">{children}</div>
        </Provider>
      </body>
    </html>
  );
}
